FROM maven:3-eclipse-temurin-11 AS maven

WORKDIR /opt/build

RUN --mount=type=bind,source=pom.xml,target=pom.xml \
    --mount=type=bind,source=src,target=src \
    --mount=type=cache,target=/root/.m2\
    mvn clean install -PdockerizedJar,ecsLogging -DskipTests=true

# This file is a Work-in-Progrss looking to start creating JARs instead of WARs for the Coop App.
# This has been tested insofar that it can launch and start.
# It is not yet tested or assertained if this change has secondary effects, such as parameters or properties made unavailable.

FROM eclipse-temurin:11 AS cooperation
ENV LOGGING_CONFIG=/opt/app/logback.xml
ADD logback4ecs.xml ${LOGGING_CONFIG}
COPY --from=maven /opt/build/target/*.jar /opt/app/app.jar
RUN useradd ind-app -MUl -u 556559423
USER ind-app
CMD ["java", "-jar", "/opt/app/app.jar"]
