spring:
  config:
    activate:
      on-profile: prod
  sql:
    init:
      platform: mysql
  datasource:
    url: ${COOPERATION_DB_URL}
    username: ${COOPERATION_DB_USER}
    password: ${COOPERATION_DB_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
    testOnBorrow: true
    validationQuery: SELECT 1
  jpa:
    open-in-view: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://dev.ntjp.se/auth/realms/coop/protocol/openid-connect/certs
