apiVersion: v1
kind: ConfigMap
metadata:
  name: cooperation-configfiles
data:
  cooperation-config-override.properties: |
    spring.datasource.url=${COOPERATION_DB_URL}
    spring.datasource.username=${COOPERATION_DB_USER}
    spring.datasource.password=${COOPERATION_DB_PASSWORD}
    se.skltp.cooperation.accesscontrol=false
    se.skltp.cooperation.api_key=bsfr
    spring.datasource.testOnBorrow=true
    spring.datasource.validationQuery=SELECT 1
  smtp.properties: |
    mail.smtp.login=${COOPERATION_MAIL_LOGIN}
    mail.smtp.host=${COOPERATION_MAIL_SERVER}
    mail.smtp.port=-1
