apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-cooperation-verify
spec:
  schedule: "{{ .Values.verifyCronJob.schedule }}"
  timeZone: "{{ .Values.verifyCronJob.timeZone }}"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            elasticGrokFilter: {{ .Values.verifyCronJob.elasticGrokFilter }}
        spec:
          volumes:
            - name: config-volume
              configMap:
                name: {{ .Values.verifyCronJob.configfilesMap }}
          containers:
            - name: cooperation-scripts
              image: "{{ .Values.repository }}cooperation-scripts:{{ .Values.container.image.tag | default $.Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.container.image.pullPolicy }}
              env:
                {{ if .Values.verifyCronJob.nodePattern }}
                - name: NODE_PATTERN
                  value: {{ .Values.verifyCronJob.nodePattern }}
                {{- end }}
                - name: NODE_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: spec.nodeName
              envFrom:
                {{- range $.Values.environment.variables._default_config_maps }}
                - configMapRef:
                    name: {{ . }}
                {{- end }}
                {{- range $.Values.environment.variables.config_maps }}
                - configMapRef:
                    name: {{ . }}
                {{- end }}
                {{- range $.Values.environment.variables.secrets }}
                - secretRef:
                    name: {{ . }}
                {{- end }}
              volumeMounts:
                - name: config-volume
                  mountPath: /etc/cooperation
                  readOnly: true
              command:
                - /bin/bash
                - '-c'
                - |
                  if [[ -z $NODE_PATTERN || $NODE_NAME =~ $NODE_PATTERN ]]; then
                    cd scripts && ./verify-cooperation-k8s.sh
                  else
                    echo "Skipping: node $NODE_NAME does not match execution node pattern"
                  fi
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                runAsNonRoot: true
                runAsUser: 1000 # groovy user
                seccompProfile:
                  type: RuntimeDefault
          imagePullSecrets:
            - name: regcred

          restartPolicy: Never
