apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-cooperation-import
spec:
  schedule: "{{ .Values.importCronJob.schedule }}"
  timeZone: "{{ .Values.importCronJob.timeZone }}"
  concurrencyPolicy: Forbid
  
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            elasticGrokFilter: {{ .Values.importCronJob.elasticGrokFilter }}
        spec:
          volumes:
            - name: key-volume
              secret:
                secretName: cooperation-keys
            - name: archive-volume
              persistentVolumeClaim:
                claimName: pvc-cooperation-archive
          containers:
            - name: cooperation-scripts
              image: "{{ .Values.repository }}cooperation-scripts:{{ .Values.container.image.tag | default $.Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.container.image.pullPolicy }}
              resources:
                requests:
                  memory: 3Gi
              env:
                {{ if .Values.importCronJob.nodePattern }}
                - name: NODE_PATTERN
                  value: {{ .Values.importCronJob.nodePattern }}
                {{- end }}
                - name: NODE_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: spec.nodeName
              envFrom:
                {{- range $.Values.environment.variables._default_config_maps }}
                - configMapRef:
                    name: {{ . }}
                {{- end }}
                {{- range $.Values.environment.variables.config_maps }}
                - configMapRef:
                    name: {{ . }}
                {{- end }}
                {{- range $.Values.environment.variables.secrets }}
                - secretRef:
                    name: {{ . }}
                {{- end }}
              volumeMounts:
                - name: key-volume
                  mountPath: /home/groovy/.ssh
                - name: archive-volume
                  mountPath: {{ .Values.importCronJob.archiveDir }}
              command:
                - /bin/bash
                - '-c'
                - |
                  if [[ -z $NODE_PATTERN || $NODE_NAME =~ $NODE_PATTERN ]]; then
                    cd scripts && ./cooperation-import-k8s.sh
                  else
                    echo "Skipping: node $NODE_NAME does not match execution node pattern"
                  fi
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                runAsNonRoot: true
                runAsUser: 1000 # groovy user
                seccompProfile:
                  type: RuntimeDefault
          imagePullSecrets:
            - name: regcred
          restartPolicy: Never
