apiVersion: apps/v1
kind: Deployment
metadata:
  name: cooperation
  labels:
    {{- include "cooperation.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: cooperation
      {{- include "cooperation.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: cooperation
        elasticGrokFilter: {{ .Values.deployment.elasticGrokFilter }}
        {{- include "cooperation.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: cooperation-configfiles
      imagePullSecrets:
        - name: regcred
      containers:
        - name: cooperation
          image: "{{ .Values.repository }}cooperation:{{ .Values.container.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.container.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            failureThreshold: 15
            httpGet:
              path: coop/actuator/health/liveness
              port: http
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: coop/actuator/health/readiness
              port: http
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1000 # ind-app user
            seccompProfile:
              type: RuntimeDefault
          resources: # Block-templated memory and CPU resources.
            {{- toYaml .Values.deployment.resources | nindent 12 }}
          {{- with .Values.environment.variables }}
          {{- if .map }}
          env:
            {{- range $k, $v := .map }}
            - name: {{ $k }}
              value: {{ $v }}
            {{- end }}
          {{- end }}
          {{- end }}
          envFrom:
            {{- range .Values.environment.variables._default_config_maps }}
            - configMapRef:
                name: {{ . }}
            {{- end }}
            {{- range .Values.environment.variables.config_maps }}
            - configMapRef:
                name: {{ . }}
            {{- end }}
            {{- range .Values.environment.variables.secrets }}
            - secretRef:
                name: {{ . }}
            {{- end }}
          volumeMounts:
            - name: config-volume
              mountPath: {{ .Values.tomcat.basedir }}
              readOnly: true
