apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  annotations:
  name: cooperation-https
spec:
  routes:
    - kind: Rule
      match: Host(`{{ .Values.ingressroute.hostName }}`) && PathPrefix(`/coop/api`, `/coop/doc`)
      priority: 10
      services:
        - kind: Service
          name: service-cooperation
          passHostHeader: true
          port: 8080
          responseForwarding:
            flushInterval: 1ms
          scheme: http
          sticky:
            cookie:
              httpOnly: true
              name: cookie
              sameSite: none
              secure: true
          strategy: RoundRobin
          weight: 10
  tls:
    domains:
      - main: {{ .Values.ingressroute.hostName }}
    secretName: {{ .Values.ingressroute.hostName }}-letsencrypt
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  annotations:
  name: cooperation-http
spec:
  routes:
  - kind: Rule
    match: Host(`{{ .Values.ingressroute.hostName }}`) && PathPrefix(`/coop/api`, `/coop/doc`)
    middlewares:
      - name: cooperation-redirect-https
    services:
      - kind: Service
        name: service-cooperation
        port: 8080
