apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  annotations:
  name: cooperation-https
spec:
  routes:
    - kind: Rule
      match: Host(`{{ .Values.ingressroute.bksHostName }}`, `{{ .Values.ingressroute.apiHostName }}`) && PathPrefix(`/coop`, `/takinfo`)
      middlewares:
        - name: cooperation-ipwhitelist
        - name: cooperation-takinfo-redirect
      priority: 10
      services:
        - kind: Service
          name: service-cooperation
          passHostHeader: true
          port: 8080
          responseForwarding:
            flushInterval: 1ms
          scheme: http
          sticky:
            cookie:
              httpOnly: true
              name: cookie
              sameSite: none
              secure: true
          strategy: RoundRobin
          weight: 10
  tls:
    domains:
      - main: {{ .Values.ingressroute.bksHostName }}
    secretName: {{ .Values.ingressroute.bksHostName }}-letsencrypt
#---
#apiVersion: traefik.containo.us/v1alpha1
#kind: IngressRoute
#metadata:
#  annotations:
#  name: cooperation-http
#spec:
#  routes:
#  - kind: Rule
#    match: Host(`{{ .Values.ingressroute.bksHostName }}`, `{{ .Values.ingressroute.apiHostName }}`) && PathPrefix(`/coop`, `/takinfo`)
#    middlewares:
#      - name: cooperation-ipwhitelist
##      - name: cooperation-redirect-https
#      - name: cooperation-takinfo-redirect
#    services:
#      - kind: Service
#        name: service-cooperation
#        port: 8080
