apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  labels:
    app.kubernetes.io/instance: {{ .Chart.Name }}
  name: cooperation-takinfo-redirect
spec:
  replacePathRegex:
    regex: ^/takinfo/(.*)
    replacement: '/coop/${1}'