apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-cooperation-archive
  namespace: {{ $.Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: basic-csi
