apiVersion: v1
kind: Service
metadata:
  name: service-cooperation
  labels:
    app: cooperation
    {{- include "cooperation.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: cooperation
    {{- include "cooperation.selectorLabels" . | nindent 4 }}