apiVersion: v1
kind: Service
metadata:
  name: service-sftp
  labels:
    app: cooperation-sftp
    {{- include "cooperation.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 22
      targetPort: 22
      protocol: TCP
      name: ssh
  selector:
    app: cooperation-sftp
    {{- include "cooperation.selectorLabels" . | nindent 4 }}