repository: test/

deployment:
  replicaCount: 1
  elasticGrokFilter: coop
  resources: #{} # The no-op curly-braces can optionally replace below sub-resources.
    limits:
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 512Mi

ingressroute:
  bksHostName: env.base.url # This should be overridden and set to a reasonable URL defined in your environment.
  apiHostName: env.base.url # This should be overridden and set to a reasonable URL defined in your environment.

container:
  image:
    tag: # To override the default tag, set it here.
    pullPolicy: Always

tomcat:
  basedir: /etc/cooperation

importCronJob:
  schedule: "30 1 * * *"
  timeZone: "Europe/Stockholm"
  nodePattern: # Override to restrict execution to certain nodes
  elasticGrokFilter: cronjob
  configfilesMap: cooperation-configfiles

verifyCronJob:
  schedule: "50 5 * * *"
  timeZone: "Europe/Stockholm"
  nodePattern: # Override to restrict execution to certain nodes
  elasticGrokFilter: cronjob
  configfilesMap: cooperation-configfiles

environment:
  variables:
    _default_config_maps:
      - cooperation-configmap-default
    config_maps:
      # Nothing yet. Override to supply your own values.
    secrets:
      # Nothing yet.
    map: 
      CATALINA_OPTS: "-XX:MaxRAMPercentage=75 -Dspring.profiles.active=production -Dapp.conf.dir=/etc/cooperation"
